Fixed bug due to change in cv2.findContours
Fixed ValueError due to extra return value in cv2.findContours.
Original error:
Traceback (most recent call last):
  File "pedestrian_tracking.py", line 357, in <module>
    show_video(sys.argv[1:])
  File "pedestrian_tracking.py", line 226, in show_video
    contours, hierarchy = cv2.findContours(im_dl, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack